### ISSUE TITLE
vertical metrics

### ISSUE THREAD

**Issue by m4rc1e** [ossobuffo/didact-gothic#3]
@davelab6 @alexeiva 
The repos fonts vertical metrics do not match the ones hosted on fonts.google.com

**left: github version right: fonts.google.com version**
![screen shot 2016-12-13 at 13 45 46](https://cloud.githubusercontent.com/assets/7525512/21141077/89b6c7c2-c13b-11e6-873b-2e5abb162afb.png)

**Comment by davelab6** [comment]
Does #5 address this?

**Comment by m4rc1e** [comment]
yep, #5 fixed this.

I'll close this.
