### ISSUE TITLE
u appears shifted

### ISSUE THREAD

**Issue by m4rc1e** [ossobuffo/didact-gothic#6]
A strange metrics issue is occuring with the 'u' when I generate from the .glyphs source.

![screen shot 2017-01-10 at 12 29 18](https://cloud.githubusercontent.com/assets/7525512/21806412/04a164d2-d731-11e6-9ea2-b2dc707ebec2.png)

This issue has nothing to do with the metrics or kerning.

I will spend a little longer looking into the cause

Please regenerate the .gylphs file and test this yourself on [impallari/testing](http://www.impallari.com/testing/)

cc @davelab6

**Comment by m4rc1e** [comment]
Ok, I think I've found the problem.

The 'u' is a flipped composite of the 'n'. By decomposing the 'u', we no longer have this issue.

![screen shot 2017-01-10 at 12 38 25](https://cloud.githubusercontent.com/assets/7525512/21806555/d6307632-d731-11e6-9777-c32ea937f9c1.png)

I'll file a pr for this.

**Comment by alexeiva** [comment]
thank you @m4rc1e

**Comment by m4rc1e** [comment]
Closing, this was solved a while back
