### ISSUE TITLE
Dash does not render anymore

### ISSUE THREAD

**Issue by B-Prod** [ossobuffo/didact-gothic#8]
Hello,

Since the last update, there is an issue with the dash character (-): it is displayed as a space, so it is invisible.
![didact-gothic-dash-issue](https://cloud.githubusercontent.com/assets/682385/22243241/c0c6ed8a-e226-11e6-9d30-0a72b6cde455.png)

It causes big troubles on live Websites that uses this font, could you please make an update to fix this?

Regards,
Fabien

**Comment by m4rc1e** [comment]
![screen shot 2017-01-25 at 12 00 49](https://cloud.githubusercontent.com/assets/7525512/22289923/f6cd05d4-e2f5-11e6-940f-066c7e5ff364.png)

Confirmed.

I'll add a patch now.
